### ISSUE TITLE
Hi and Thankyou

### ISSUE THREAD

**Issue by nemosminer** [MrPlusGH/NemosMinerPlus#3]
Hi MrPlus 

thank you for your great work i have included all your new features in my latest code i have added you to readme along side aaronsace and i.. also i implemented your donation feature from http://mytestenv.alwaysdata.net/servefiles/Donation.json : ) very much appreciated

Best Regards
Nemo

**Comment by MrPlusGH** [comment]
Hi Nemo,

Thank you! This is great collaboration.
So happy you like and implemented the features. Hope NemosMiner users will like it.
I tried to get in touch on Bitcointalk. You might not have received my messages as I am a newbie there.
Could you please get in touch via PM there? 

+MrPlus
